output:
  sort-results: true

run:
  timeout: 3m
  build-tags:
  - withebpf
  - docs

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Ignore check: Packages must have a package comment
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck
    # FIXME temporarily suppress. See issue #540
    - text: "SA1016: (syscall.SIGKILL|os.Kill) cannot be trapped \\(did you mean syscall.SIGTERM\\?\\)"
      linters:
      - staticcheck
    # FIXME temporarily suppress. See issue #541
    - text: "SA1019: grpc.WithDialer is deprecated: use WithContextDialer instead."
      linters:
        - staticcheck

linters:
  disable-all: true
  enable:
  - gofumpt
  - stylecheck
  - staticcheck
  - errorlint

linters-settings:
  gofumpt:
    lang-version: "1.18"
  staticcheck:
    go: "1.18"
    checks: ["all"]
  stylecheck:
    go: "1.18"
    checks: ["all"]
  errorlint:
    # https://github.com/polyfloyd/go-errorlint
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    errorf: true
    # Check for plain type assertions and type switches (errors.As must be used).
    asserts: true
    # Check for plain error comparisons (errors.Is must be used)
    comparison: true
