services:
  ig:
    image: ${DESKTOP_PLUGIN_IMAGE}
    privileged: true
    network_mode: host
    userns_mode: host
    pid: host
    volumes:
      - /:/host
      # fanotify /run/containerd/io.containerd.runtime.v2.task/moby/d29.../init.pid
      - /run:/run
    environment:
      HOST_ROOT: /host

